const EnvVars = {
  AWS_PROFILE: process.env.AWS_PROFILE,
  AWS_ACCOUNT: process.env.AWS_ACCOUNT,
  AWS_REGION: process.env.AWS_REGION,
  DEPLOYMENT_ENV: process.env.DEPLOYMENT_ENV,
  KMS_KEY_ALIAS: process.env.KMS_KEY_ALIAS,
  KMS_KEY_ALIAS_STATION: process.env.KMS_KEY_ALIAS_STATION,
  USER_POOL_ID: process.env.USER_POOL_ID,
  USER_POOL_ID_STATION: process.env.USER_POOL_ID_STATION,
  USER_POOL_WEB_CLIENT_ID: process.env.USER_POOL_WEB_CLIENT_ID,
  USER_POOL_WEB_CLIENT_ID_STATION: process.env.USER_POOL_WEB_CLIENT_ID_STATION,
  MONGO_CLUSTER: process.env.MONGO_CLUSTER,
  MONGO_USERNAME: process.env.MONGO_USERNAME,
  MONGO_PASSWORD: process.env.MONGO_PASSWORD,
  SENDGRID_API_KEY: process.env.SENDGRID_API_KEY,
  SENDGRID_WELCOME_TEMPLATE_ID: process.env.SENDGRID_WELCOME_TEMPLATE_ID,
  SENDGRID_FORGOTPASSWORD_TEMPLATE_ID: process.env.SENDGRID_FORGOTPASSWORD_TEMPLATE_ID,
}

module.exports = EnvVars
